version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
  php:
    build: './php/'
    depends_on:
           - db
    networks:
        - backend
    volumes:
         - ./docker/www/:/var/www/html

  apache:
      build: './apache/'
      depends_on:
          - php
          - db
      networks:
          - frontend
          - backend
      ports:
         - "8080:80"
      volumes:
         - ./docker/www/:/var/www/html

networks:
    frontend:
    backend:
